export const UserModel = {
  userId: 9900,
  firstName: 'Ruqayaah',
  lastName: 'Sabitu',
  email: 'aderinolaruqayaah@gmail.com',
  // phone: 08189706105,
  password: 'awesoma',
  // dob: 1960-10-01,
  age: 61,
  address: '3, Ibiade Street, Isokan Estate, Ota, Ogun State.',
  university: 'University of Ibadan',
  course: 'Geology',
  cv_url: 'https://res.cloudinary.com/demo/image/upload/example.pdf',
  photo_url: 'https://res.cloudinary.com/demo/image/upload/example.jpg',
  created_at: '',
  updated_at: '',
  cgpa: 5.00,
  batchId: 1,
  test_score: 100,
};

export const userModel = [
  {
    userId: '719a6c77-f46e-43ba-bbdb-fd7fa890af71',
    fullName: 'Peculiar Erhis',
    email: 'perhis@gmail.com',
    // phone: 08126432823,
    password: 'Princess@26',
    dob: '1996-04-26',
    age: 24,
    address: '3 Sabo Ave, Yaba, Lagos',
    university: 'University of Nigeria',
    courseOfStudy: 'Computer Science',
    cgpa: 5.00,
    batchId: 2,
    cvId: 'example_pdf',
    cvUrl: 'https://res.cloudinary.com/demo/image/upload/example_pdf.pdf',
    photoId: 'example_jpg',
    photoUrl: 'https://res.cloudinary.com/demo/image/upload/example_jpg.jpg',
    testScore: 15,
    createdAt: '',
    updatedAt: '',
  },
];
